Add colored user roles
dataware-tools/app-user-manager pull request #366
Opened 2022-08-05 00:57 UTC by onose004

## What?
(概要など)
- ユーザ管理画面でユーザロールをその名前のハッシュ値に基づいて色を変更する機能を追加

## Why?
(モチベーションなど)
- 視認性向上のため

## See also [Optional]
- https://github.com/dataware-tools/app-common/pull/443
## Screenshot or video [Optional]

2022-08-05 09:43 UTC, WatanabeToshimitsu commented
@onose004 
CI のエラーの一部は、CI 上では app-common の古いバージョンがインストールされていることに起因しています
なので、ローカル環境の方で`npm install @dataware-tools/app-common@latest` 等を実行して、package.json と package-lock.json 上の app-common のバージョン情報を書き換えて、それをコミットしてもらえれば、少しエラーがスッキリすると思います

以上のことを実行した上で、恐らく以下のエラーが残ると思います
```
src/components/organisms/UserListItem.tsx:77:15 - error TS2578: Unused '@ts-expect-error' directive.

77               // @ts-expect-error to be fixed
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/organisms/UserListItem.tsx:79:26 - error TS2345: Argument of type 'Option[]' is not assignable to parameter of type 'Roles'.
  Type 'Option' is not assignable to type '{ role_id: number; name: string; }'.
    Type 'string' is not assignable to type '{ role_id: number; name: string; }'.

79                 onChange(newValues);
                            ~~~~~~~~~
```

### 77行目のエラーについて

[@ts-expect-error コメント](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#-ts-expect-error-comments)の仕様によるエラーです
`@ts-expect-error` コメントは、直下の行に対し、tsc が吐くエラーを無視させる効果があります（`@ts-ignore` コメントと同じ効果です）　それに加えて、直下の行に対して tsc がエラーを吐かない場合、そのコメント自体が tsc によってエラーとして検出されるようになってます
今回は、78 行目にエラーがなかったので、77行目のコメント自体がエラーになっています　なので、該当行を削除することでエラーを解消できます

### 79行目のエラーについて
まず、このエラーが起きている理屈を解説します　特に必要なければ === ここまで解説 === まで飛ばしてください
`MultiSelect` コンポーネントの props である `onChange` 関数の二つ目の引数が、そのまま `UserListItemPresentation` コンポーネントの props である `onChange` 関数の引数として渡されているところに問題があります

`MultiSelect` コンポーネントの props である `onChange` 関数の二つ目の引数の型は Option[] 型、すなわち
```
 ( string | number | { [key:string]: any, color?: string, name?: string} )[]
```
型です
> `[key: string]: any` に関してわからない場合は、[サバイバルTypescript のインデックス型のページ](https://typescriptbook.jp/reference/values-types-variables/object/index-signature)を参照してください

Union 型はざっくり言えば「型のOR」なので、括弧を展開することで以下のようにも表せます
```
string[] | number[] | { [key:string]: any, color?: string, name?: string}[]
```

また、`UserListItemPresentation` コンポーネントの props である `onChange` 関数の引数の方は Roles 型、すなわち
```
{  role_id: number;  name: string; }[]; 
```
型です

Option 型の Union を展開した形と Roles 型を見比べると、Roles 型は Option[] 型の部分集合になってるのがわかるかと思います
すなわち、Roles 型しか引数として受け入れない関数は、Option[] 型を引数として受け入れられません　なので、tsc がそれを検知してエラーを吐いてます
=== ここまで解説 ===

肝心の解決法ですが、[MultiSelect コンポーネントに props として渡している getOptionLabel 関数と、getOptionColor 関数の引数に対する Option 型の指定](https://github.com/dataware-tools/app-user-manager/pull/366/files#diff-09cca9383a482722fb6387e03b34b876b2566179cb95a5df61073507e2fbee41R89)を外すと色々うまくいくと思います　この方法で解決すると、98行目の `@ts-expect-error` コメントも外せると思います

これで解決される理由を述べると、あまりにも文章が長くなるのでアレですが、恐らくジェネリクス型について調べてもらいながら、MultiSelect の型の元になっている MUI の Autocomplete の型を追ってもらえれば理解できる気がしています　気になるようであればそんな感じで調べるなり、僕でよければいつでも僕に聞いてください


それと、今回の変更は、がっつりUIの見た目が変わる変更なので、恐らく loki によるビジュアルリグレッションテストが落ちると思います！　そこに関しても、可能なら修正してコミットしてもらえると嬉しいです！

2022-08-24 06:27 UTC, WatanabeToshimitsu requested changes
現状だと、ハッシュから色相が近い色が生成されてしまた場合にかなり判別しづらいので、そこの修正をお願いします！（詳しくは該当部のコメントを参照してください）

2022-08-24 06:27 UTC, WatanabeToshimitsu commented on src/components/organisms/UserListItem.tsx
> +                if (typeof option !== "string" && typeof option !== "number") {
もし異常系を想定して型の検査を行なっているのなら大丈夫なんですが、option の型が `string | number | {name: string, role_id: string }` だった時に、tsc のエラーを回避するための方法として typeof による型検査を行なっているのなら、現在は option の型が `{name: string, role_id:string}` になっているので、ここの型検査は不要です

2022-08-24 06:27 UTC, WatanabeToshimitsu commented on src/components/organisms/UserListItem.tsx
> +                  return `hsl(${hue}, 50%, 80%)`;
彩度と明度も一定の範囲でハッシュ等の値に応じて動かせるようにすると、今よりも色分けが明確になると思うので、そのようにできると嬉しいです！
（こっちの方で試してみた感じ、彩度の加減を30~40 程度にしておいて、明度の下限を 50 ~60 程度にしておけば文字色とも背景色とも分別できるように見受けらたので、参考までに）

2022-08-24 06:27 UTC, WatanabeToshimitsu commented on src/components/organisms/UserListItem.tsx
> +                if (typeof option !== "string" && typeof option !== "number") {
同上です

2022-08-26 07:20 UTC, onose004 commented
フィードバックありがとうございました！
一応、彩度と明度も違いがでるように色々数値を変えてみましたが、明確な区別はつきにくそうですね。
ハッシュ値だとどうしても、そうなりがちです。
ハッシュ値を使わず各 role ごとに色を指定するということもできそうですが、それは後々需要があった際に対応する方針でもよいと考えていますがどうでしょうか？
<img width="488" alt="スクリーンショット 2022-08-26 16 16 44" src="https://user-images.githubusercontent.com/8692594/186845114-dba48cec-ceb1-406e-a947-57a9ee079525.png">

2022-08-26 08:20 UTC, merged